<template>
  <section>
    <h2 class="underline text-3xl mb-4">Términos y condiciones</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim cras tincidunt lobortis feugiat vivamus at. Dolor magna eget est lorem ipsum dolor sit. Lacus sed viverra tellus in hac. Lorem ipsum dolor sit amet consectetur adipiscing. Tincidunt lobortis feugiat vivamus at augue. Mollis aliquam ut porttitor leo a diam. Suscipit tellus mauris a diam maecenas sed enim ut sem. Volutpat commodo sed egestas egestas fringilla. Ullamcorper malesuada proin libero nunc. Eu facilisis sed odio morbi quis commodo. Mus mauris vitae ultricies leo integer. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Vel orci porta non pulvinar. Nulla facilisi etiam dignissim diam quis. Pulvinar pellentesque habitant morbi tristique senectus et. Rhoncus mattis rhoncus urna neque viverra justo.</p>
    <p>Leo vel fringilla est ullamcorper eget nulla facilisi. Tincidunt ornare massa eget egestas. Lobortis scelerisque fermentum dui faucibus in ornare quam. In hendrerit gravida rutrum quisque non tellus orci ac. Eget duis at tellus at urna condimentum mattis pellentesque. Massa placerat duis ultricies lacus sed. Vitae aliquet nec ullamcorper sit. Quam id leo in vitae turpis massa sed elementum tempus. Vitae nunc sed velit dignissim sodales ut eu sem. Ultrices sagittis orci a scelerisque purus. Eget sit amet tellus cras adipiscing enim eu turpis. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Auctor eu augue ut lectus arcu bibendum at varius vel. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Sapien et ligula ullamcorper malesuada proin libero nunc. Tellus id interdum velit laoreet id donec ultrices.</p>
    <p>At imperdiet dui accumsan sit amet nulla facilisi. Vehicula ipsum a arcu cursus vitae congue. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Odio aenean sed adipiscing diam donec adipiscing. Dignissim enim sit amet venenatis urna cursus eget. Ante metus dictum at tempor commodo ullamcorper. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eu consequat ac felis donec et odio pellentesque diam. Urna nec tincidunt praesent semper. Id porta nibh venenatis cras sed felis eget.</p>
    <p>Turpis massa sed elementum tempus egestas sed. Non arcu risus quis varius quam quisque id diam vel. Ante in nibh mauris cursus mattis. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Rhoncus mattis rhoncus urna neque viverra justo. Donec adipiscing tristique risus nec feugiat. Erat velit scelerisque in dictum. Sed id semper risus in hendrerit gravida rutrum quisque non. Sed libero enim sed faucibus turpis in eu mi. Imperdiet dui accumsan sit amet nulla facilisi morbi.</p>
    <p>Purus in massa tempor nec feugiat nisl. Pharetra et ultrices neque ornare aenean euismod. Consequat ac felis donec et. Nisl tincidunt eget nullam non nisi est sit amet. Ultrices sagittis orci a scelerisque purus semper eget. Consectetur purus ut faucibus pulvinar elementum integer. Eget gravida cum sociis natoque penatibus et. Justo laoreet sit amet cursus. Congue mauris rhoncus aenean vel. Porttitor leo a diam sollicitudin tempor. Augue eget arcu dictum varius. Lectus urna duis convallis convallis tellus id interdum velit. Justo nec ultrices dui sapien eget mi. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dignissim cras tincidunt lobortis feugiat vivamus at. Dolor magna eget est lorem ipsum dolor sit. Lacus sed viverra tellus in hac. Lorem ipsum dolor sit amet consectetur adipiscing. Tincidunt lobortis feugiat vivamus at augue. Mollis aliquam ut porttitor leo a diam. Suscipit tellus mauris a diam maecenas sed enim ut sem. Volutpat commodo sed egestas egestas fringilla. Ullamcorper malesuada proin libero nunc. Eu facilisis sed odio morbi quis commodo. Mus mauris vitae ultricies leo integer. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Vel orci porta non pulvinar. Nulla facilisi etiam dignissim diam quis. Pulvinar pellentesque habitant morbi tristique senectus et. Rhoncus mattis rhoncus urna neque viverra justo.</p>
    <p>Leo vel fringilla est ullamcorper eget nulla facilisi. Tincidunt ornare massa eget egestas. Lobortis scelerisque fermentum dui faucibus in ornare quam. In hendrerit gravida rutrum quisque non tellus orci ac. Eget duis at tellus at urna condimentum mattis pellentesque. Massa placerat duis ultricies lacus sed. Vitae aliquet nec ullamcorper sit. Quam id leo in vitae turpis massa sed elementum tempus. Vitae nunc sed velit dignissim sodales ut eu sem. Ultrices sagittis orci a scelerisque purus. Eget sit amet tellus cras adipiscing enim eu turpis. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Auctor eu augue ut lectus arcu bibendum at varius vel. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Sapien et ligula ullamcorper malesuada proin libero nunc. Tellus id interdum velit laoreet id donec ultrices.</p>
    <p>At imperdiet dui accumsan sit amet nulla facilisi. Vehicula ipsum a arcu cursus vitae congue. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Odio aenean sed adipiscing diam donec adipiscing. Dignissim enim sit amet venenatis urna cursus eget. Ante metus dictum at tempor commodo ullamcorper. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Eu consequat ac felis donec et odio pellentesque diam. Urna nec tincidunt praesent semper. Id porta nibh venenatis cras sed felis eget.</p>
    <p>Turpis massa sed elementum tempus egestas sed. Non arcu risus quis varius quam quisque id diam vel. Ante in nibh mauris cursus mattis. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Rhoncus mattis rhoncus urna neque viverra justo. Donec adipiscing tristique risus nec feugiat. Erat velit scelerisque in dictum. Sed id semper risus in hendrerit gravida rutrum quisque non. Sed libero enim sed faucibus turpis in eu mi. Imperdiet dui accumsan sit amet nulla facilisi morbi.</p>
    <p>Purus in massa tempor nec feugiat nisl. Pharetra et ultrices neque ornare aenean euismod. Consequat ac felis donec et. Nisl tincidunt eget nullam non nisi est sit amet. Ultrices sagittis orci a scelerisque purus semper eget. Consectetur purus ut faucibus pulvinar elementum integer. Eget gravida cum sociis natoque penatibus et. Justo laoreet sit amet cursus. Congue mauris rhoncus aenean vel. Porttitor leo a diam sollicitudin tempor. Augue eget arcu dictum varius. Lectus urna duis convallis convallis tellus id interdum velit. Justo nec ultrices dui sapien eget mi. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla.</p>
  </section>
</template>
<style lang="scss" scoped>
@layer terms{
    p {
        @apply pb-4;
    }
}
</style>